<!-- default template -->
<section>
  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ut velit faucibus, tempus mauris sit amet, feugiat nisi. Mauris tincidunt vehicula orci, vitae viverra mauris venenatis volutpat. Vivamus leo tellus, ullamcorper commodo diam et, sollicitudin tincidunt sem. Nulla facilisi. Maecenas porttitor lobortis sapien. Nunc sit amet augue diam. Quisque sodales iaculis ante, non gravida dui molestie ullamcorper. Nulla vulputate venenatis tincidunt. Mauris sed convallis urna. Praesent tempus, risus sed congue consectetur, metus urna tincidunt augue, quis dapibus ligula lectus id metus. Suspendisse in nibh eget massa rutrum scelerisque id sit amet diam. Aenean vehicula nibh sit amet elementum luctus. Cras ornare aliquet metus et porttitor. Nunc vel massa sed ante mattis sollicitudin. Proin volutpat odio est, eget porttitor ante auctor at.</p>

  <blockquote>
    <p>Pellentesque rutrum pretium lacus, a luctus nulla sodales at. Etiam arcu elit, ornare et rhoncus et, lobortis vulputate ante. Cras nunc ligula, malesuada in consectetur bibendum, consectetur consequat nisi. Fusce pretium lacinia purus ac congue. Nunc id turpis est. Mauris ornare risus eget augue eleifend pharetra. Suspendisse a tellus ut augue vulputate aliquet. In imperdiet turpis lacus, et volutpat nulla condimentum quis.</p>
    <cite>Dave Smith</cite>
  </blockquote>

  <figure>
    <img src="/img/figure.jpg" />
    <figcaption>Proin dignissim ante non porta scelerisque. Donec iaculis vulputate nunc, at lobortis diam suscipit in. Pellentesque condimentum nisi lectus, eu eleifend nisi ullamcorper a. Vestibulum tempus est vitae auctor varius. Sed nec eros a ligula accumsan pharetra. Donec bibendum nec sapien eget elementum. Duis mi dolor, euismod id sapien in, interdum sollicitudin dui. Mauris blandit libero at velit consequat, in adipiscing dolor pharetra. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Sed et augue eget arcu mollis convallis vitae a diam.</figcaption>
  </figure>

  <p>Sed eget sagittis diam, nec bibendum diam. Nunc in vestibulum sapien. Nunc non vulputate odio, faucibus porta mi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla luctus bibendum erat id mollis. Proin venenatis rutrum augue ac rutrum. Sed nisl dui, porta a ultrices in, sollicitudin sit amet felis. Mauris sagittis varius sem, a posuere nibh ultricies et. Aenean quis neque sem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut velit enim. Pellentesque quis lacus lacinia mi semper porta.</p>

  <p>Nam quis mauris porttitor, tristique ipsum ut, condimentum tellus. Donec nec neque porta, commodo leo hendrerit, mattis metus. Aliquam sollicitudin porttitor sem, nec eleifend libero pharetra at. Aenean varius bibendum enim, sollicitudin pulvinar quam lacinia vitae. Curabitur dictum, ipsum ac ullamcorper venenatis, massa velit congue lacus, a varius nisl diam sed leo. Sed ullamcorper non purus sed posuere. Curabitur laoreet, turpis id congue sodales, orci sem sagittis nunc, id ultricies turpis magna et turpis. Nam facilisis vehicula facilisis. Ut auctor blandit felis, in eleifend felis hendrerit in. Curabitur at lorem ut mauris scelerisque ullamcorper sed ut turpis. Integer euismod, arcu et varius pellentesque, odio arcu convallis nulla, ac auctor nisl mi id mauris. Ut auctor felis id nunc placerat, fringilla ultrices leo fringilla. Phasellus et nunc ultrices, mattis magna eu, accumsan lacus.</p>
</section>